# Generated by Django 3.1.3 on 2020-12-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
    ]
